### ISSUE TITLE
GOPRO dataset not downloadable

### ISSUE THREAD

**Issue by Fahad014** [York-SDCNLab/Ghost-DeblurGAN#2]
I tried to download the dataset but it fails at 99% every time. My internet speed is good and of high config. Later on I found this message. Can you please mention away to download the dataset? 
Thank you.
![image](https://user-images.githubusercontent.com/115699449/195555124-12124a36-0e32-4c1e-8764-1694bf1460a9.png)

**Comment by yorklyb** [comment]
Hi, I just tried the link we provided and it still works. If you are sure that your network works well to download the other data saved on google drive (that is, the problem is not with your network like you don't have to use a VPN), you could try to reach the link given by the authors of deblurgan v2 (https://github.com/VITA-Group/DeblurGANv2) as we actually used the same linear GoPro dataset as them.
